name: Build & Release

on:
  push:
    branches: [ "**" ]          # build/test on every push
    tags:
      - 'v*.*.*'                 # ALSO run when a version tag is pushed
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [11-jdk, 17-jdk, 21-jdk]
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ./gradlew
      - run: ./gradlew build test --stacktrace

  release:
    # run only when this push is a tag that starts with "v"
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build release JAR
        run: ./gradlew build --stacktrace

      - name: Create GitHub Release and upload JAR
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}       # the pushed tag, e.g. v1.0.0
          name: Release ${{ github.ref_name }}
          files: build/libs/*.jar                # attach built jars as assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
